version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    target-branch: dependency-updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: dependency-updates
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    target-branch: dependency-updates
