version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    target-branch: dependency-updates
    labels:
      - dependencies
      - python
      - type:maintenance
    groups:
      django:
        patterns:
        - 'django*'
      pytest:
        patterns:
        - 'pytest*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    target-branch: dependency-updates
    labels:
      - dependencies
      - github_actions
      - type:maintenance
    groups:
      # create a single pull request containing all updates for GitHub Actions
      github-actions:
        patterns:
        - '*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    target-branch: dependency-updates
    labels:
      - dependencies
      - javascript
      - type:maintenance
    groups:
      react:
        patterns:
        - 'react*'
      development-dependencies:
        dependency-type: 'development'
