version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    target-branch: dependency-updates
    labels:
      - dependencies
      - python
      - type:maintainance
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: dependency-updates
    labels:
      - dependencies
      - github_actions
      - type:maintainance
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    target-branch: dependency-updates
    labels:
      - dependencies
      - javascript
      - type:maintainance
