from django.urls import path, re_path

from ..views import (
    IntegrationCreateView,
    IntegrationDeleteView,
    IntegrationUpdateView,
    IntegrationWebhookView,
    InviteDeleteView,
    IssueDetailView,
    IssueSendView,
    IssueUpdateView,
    MembershipCreateView,
    MembershipDeleteView,
    MembershipUpdateView,
    ProjectAnswersExportView,
    ProjectAnswersView,
    ProjectCancelView,
    ProjectCreateImportView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectErrorView,
    ProjectExportView,
    ProjectJoinView,
    ProjectLeaveView,
    ProjectQuestionsView,
    ProjectsView,
    ProjectUpdateCatalogView,
    ProjectUpdateImportView,
    ProjectUpdateInformationView,
    ProjectUpdateParentView,
    ProjectUpdateTasksView,
    ProjectUpdateView,
    ProjectUpdateViewsView,
    ProjectViewExportView,
    ProjectViewView,
    SiteProjectsView,
    SnapshotCreateView,
    SnapshotRollbackView,
    SnapshotUpdateView,
)

urlpatterns = [
    path('',
            ProjectsView.as_view(), name='projects'),
    path('all/',
            SiteProjectsView.as_view(), name='site_projects'),

    path('create/',
            ProjectCreateView.as_view(), name='project_create'),
    path('join/<path:token>/',
            ProjectJoinView.as_view(), name='project_join'),
    path('cancel/<path:token>/',
            ProjectCancelView.as_view(), name='project_cancel'),
    path('import/',
            ProjectCreateImportView.as_view(), name='project_create_import'),
    re_path(r'^import/(?P<format>[a-z-]+)/$',
            ProjectCreateImportView.as_view(), name='project_create_import'),

    path('<int:pk>/',
            ProjectDetailView.as_view(), name='project'),
    path('<int:pk>/update/',
            ProjectUpdateView.as_view(), name='project_update'),
    path('<int:pk>/update/information/',
            ProjectUpdateInformationView.as_view(), name='project_update_information'),
    path('<int:pk>/update/catalog/',
            ProjectUpdateCatalogView.as_view(), name='project_update_catalog'),
    path('<int:pk>/update/parent/',
            ProjectUpdateParentView.as_view(), name='project_update_parent'),
    path('<int:pk>/update/tasks/',
            ProjectUpdateTasksView.as_view(), name='project_update_tasks'),
    path('<int:pk>/update/views/',
            ProjectUpdateViewsView.as_view(), name='project_update_views'),
    path('<int:pk>/delete/',
            ProjectDeleteView.as_view(), name='project_delete'),
    path('<int:pk>/leave/',
            ProjectLeaveView.as_view(), name='project_leave'),
    re_path(r'^(?P<pk>[0-9]+)/export/(?P<format>[a-z-]+)/$',
            ProjectExportView.as_view(), name='project_export'),
    path('<int:pk>/import/',
            ProjectUpdateImportView.as_view(), name='project_update_import'),
    re_path(r'^(?P<pk>[0-9]+)/import/(?P<format>[a-z-]+)/$',
            ProjectUpdateImportView.as_view(), name='project_update_import'),

    path('<int:project_id>/memberships/create/',
            MembershipCreateView.as_view(), name='membership_create'),
    path('<int:project_id>/memberships/<int:pk>/update/',
            MembershipUpdateView.as_view(), name='membership_update'),
    path('<int:project_id>/memberships/<int:pk>/delete/',
            MembershipDeleteView.as_view(), name='membership_delete'),
    path('<int:project_id>/invite/<int:pk>/delete/',
            InviteDeleteView.as_view(), name='invite_delete'),

    re_path(r'^(?P<project_id>[0-9]+)/integrations/create/(?P<provider_key>[a-z]+)/$',
            IntegrationCreateView.as_view(), name='integration_create'),
    path('<int:project_id>/integrations/<int:pk>/update/',
            IntegrationUpdateView.as_view(), name='integration_update'),
    path('<int:project_id>/integrations/<int:pk>/delete/',
            IntegrationDeleteView.as_view(), name='integration_delete'),
    path('<int:project_id>/integrations/<int:pk>/webhook/',
            IntegrationWebhookView.as_view(), name='integration_webhook'),

    path('<int:project_id>/issues/<int:pk>/',
            IssueDetailView.as_view(), name='issue'),
    path('<int:project_id>/issues/<int:pk>/update/',
            IssueUpdateView.as_view(), name='issue_update'),
    path('<int:project_id>/issues/<int:pk>/send/',
            IssueSendView.as_view(), name='issue_send'),

    path('<int:project_id>/snapshots/create/',
            SnapshotCreateView.as_view(), name='snapshot_create'),
    path('<int:project_id>/snapshots/<int:pk>/update/',
            SnapshotUpdateView.as_view(), name='snapshot_update'),
    path('<int:project_id>/snapshots/<int:pk>/rollback/',
            SnapshotRollbackView.as_view(), name='snapshot_rollback'),

    path('<int:pk>/answers/',
            ProjectAnswersView.as_view(), name='project_answers'),
    re_path(r'^(?P<pk>[0-9]+)/answers/export/(?P<format>[a-z]+)/$',
            ProjectAnswersExportView.as_view(), name='project_answers_export'),

    path('<int:pk>/snapshots/<int:snapshot_id>/answers/',
            ProjectAnswersView.as_view(), name='project_answers'),
    re_path(r'^(?P<pk>[0-9]+)/snapshots/(?P<snapshot_id>[0-9]+)/answers/export/(?P<format>[a-z]+)/$',
            ProjectAnswersExportView.as_view(), name='project_answers_export'),

    path('<int:pk>/views/<int:view_id>/',
            ProjectViewView.as_view(), name='project_view'),
    re_path(r'^(?P<pk>[0-9]+)/views/(?P<view_id>[0-9]+)/export/(?P<format>[a-z]+)/$',
            ProjectViewExportView.as_view(), name='project_view_export'),

    path('<int:pk>/snapshots/<int:snapshot_id>/views/<int:view_id>/',
            ProjectViewView.as_view(), name='project_view'),
    re_path(r'^(?P<pk>[0-9]+)/snapshots/(?P<snapshot_id>[0-9]+)/views/(?P<view_id>[0-9]+)/export/(?P<format>[a-z]+)/$',
            ProjectViewExportView.as_view(), name='project_view_export'),

    re_path(r'^(?P<pk>[0-9]+)/questions/',
            ProjectQuestionsView.as_view(), name='project_questions'),
    re_path(r'^(?P<pk>[0-9]+)/error/',
            ProjectErrorView.as_view(), name='project_error'),
]
