name: CI

on:
  push:
    branches:
      - master
      - 'releases/**'
    tags:
      - '*.*.*'
  pull_request:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONDONTWRITEBYTECODE: 1

jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip
    - run: python -m pip install --upgrade pip
    - run: pip install -e .[dev]
    - name: Set up pre-commit cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: lint-${{ hashFiles('.pre-commit-config.yaml') }}
    - run: pre-commit run --all-files --color=always

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.7', '3.11']
        db-backend: [mysql, postgres, sqlite3]
      fail-fast: false # TODO: for debugging tests only
    name: "Build (Python: ${{ matrix.python-version }}, DB: ${{ matrix.db-backend }})"
    needs: [lint]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install --yes pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended lmodern librsvg2-bin gettext
        python -m pip install --upgrade pip
        pandoc --version
    - name: Install rdmo
      run: |
        pip install -e .[ci]
      if: matrix.db-backend == 'sqlite3'
    - name: Install rdmo[mysql] and start mysql
      run: |
        pip install -e .[ci,mysql]
        sudo systemctl start mysql.service
      if: matrix.db-backend == 'mysql'
    - name: Install rdmo[postgres] and start postgresql
      run: |
        pip install -e .[ci,postgres]
        sudo systemctl start postgresql.service
        pg_isready
        sudo -u postgres psql --command="CREATE USER postgres_user PASSWORD 'postgres_password' CREATEDB"
      if: matrix.db-backend == 'postgres'
    - name: Prepare Env
      run: |
        cp testing/config/settings/${{ matrix.db-backend }}.py testing/config/settings/local.py
        cp -r testing/media testing/media_root
        mkdir testing/log
    - name: Run Tests
      run: |
        pytest -p no:cacheprovider --cov --reuse-db --numprocesses=auto --dist=loadscope
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: '${{ matrix.db-backend }}: ${{ matrix.python-version }}'
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Run Coveralls finish
      run: |
        pip install coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dev-setup:
    # Ref: structlog (MIT licensed) <https://github.com/hynek/structlog/blob/main/.github/workflows/ci.yml>
    name: "Test dev setup on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - run: python -Im pip install -e .[dev]
      - run: python -Ic 'import rdmo; print(rdmo.__version__)'
